# Generated by Django 3.2.9 on 2021-11-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthplace', models.CharField(max_length=255)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
