# Generated by Django 3.2.9 on 2021-11-09 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.artist'),
        ),
    ]
