# Generated by Django 3.2.9 on 2021-11-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_auto_20211110_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
