# Generated by Django 3.2.9 on 2021-11-11 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
